### ISSUE TITLE
마감날짜 입력 방법 논의 + 새스터디 입력 UI 피그마 작성중

### ISSUE THREAD

**Issue by wade3420** [side-project-moa/MOA-FE#8]
마감날짜 입력 방법 논의 + 새스터디 입력 UI 피그마 작성중

**Comment by wade3420** [comment]
이거 회의 언제하죠!!!!!!

**Comment by deprecated-hongbiii** [comment]
낼 오후에 할까요??

**Comment by deprecated-hongbiii** [comment]
- 마감날짜 입력: 키보드 입력으로 하기로 함
- 새 스터디 페이지 & 스터디 상세 페이지 UI 작업 완료

Figma 링크: https://www.figma.com/file/6dkezbO8xPxH8rySGhrIBl/MOA?node-id=0%3A1
